SET SCHEMA FN71677;

CREATE VIEW V_EMPINFO
AS
SELECT D.DEPTNAME, E.FNAME || ' ' || E.LNAME AS EMPNAME, J.title AS POSITION
FROM DEPARTMENTS D, EMPLOYEES E, JOBS J
WHERE D.DEPTNO = E.DEPTNO AND E.JOBID = J.JOBID;

SELECT * FROM V_EMPINFO
WHERE DEPTNAME = 'IT';

CREATE VIEW V_DEPT_JOBHISTORY
AS
SELECT D.DEPTNAME, E.FNAME || ' ' || E.LNAME AS EMPNAME, H.start_date, H.end_date, J.TITLE AS POSITION
FROM DEPARTMENTS D, JOBHISTORY H, JOBS J, EMPLOYEES E
WHERE D.DEPTNO = H.DEPTNO AND H.JOBID = J.JOBID AND H.EMPNO = E.EMPNO;

SELECT * FROM V_DEPT_JOBHISTORY
WHERE DEPTNAME = 'IT';
