CREATE TABLE USERS(
  USERNAME CHAR(3) NOT NULL PRIMARY KEY,
  NAME VARCHAR(50)
);

CREATE TABLE MESSAGES(
    ID INT NOT NULL PRIMARY KEY,
    TEXT VARCHAR(200) NOT NULL,
    USERNAME CHAR(3) NOT NULL
);

ALTER TABLE MESSAGES
ADD CONSTRAINT FK_MSG_USR
FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
ON DELETE CASCADE;

DELETE FROM USERS
WHERE USERNAME = 'ABC';

CREATE VIEW V_USERS
AS
    SELECT USERNAME, NAME
    FROM USERS
    WHERE USERNAME LIKE 'C%';

SELECT * FROM V_USERS;

INSERT INTO V_USERS VALUES ('ABC', 'SFSDFSDFSD');

SELECT * FROM SYSCAT.VIEWS
WHERE VIEWSCHEMA = 'DB2ADMIN';

CREATE FUNCTION CNT_EMP(P_WORKDEPT CHAR(3))
RETURNS INT -- TABLE(ID INT, NAME VARCHAR)
RETURN
SELECT COUNT(*) AS CNT
FROM EMPLOYEE
WHERE WORKDEPT = P_WORKDEPT;

SELECT  DB2ADMIN.CNT_EMP(DEPTNO) FROM DEPARTMENT;

CREATE FUNCTION NAME_EMP(P_EMPNO CHAR(6))
RETURNS VARCHAR(30) 
RETURN
SELECT FIRSTNME || ' ' || LASTNAME
FROM EMPLOYEE
WHERE EMPNO = P_EMPNO;

SELECT  DB2ADMIN.NAME_EMP(EMPNO) FROM EMPLOYEE;

VALUES  DB2ADMIN.NAME_EMP('000010');

SELECT  DB2ADMIN.NAME_EMP('000030') FROM SYSIBM.SYSDUMMY1;

CREATE FUNCTION T_EMP(P_EMPNO CHAR(6))
RETURNS TABLE(NAME VARCHAR(30), SALARY DECIMAL(9,2))
RETURN
SELECT FIRSTNME || ' ' || LASTNAME, SALARY
FROM EMPLOYEE
WHERE EMPNO = P_EMPNO;

SELECT *
FROM TABLE(DB2ADMIN.T_EMP('000030'))T ;

CREATE TABLE AUDIT(
    USERNAME CHAR(20) NOT NULL,
    TABLE VARCHAR(30) NOT NULL,
    EMPNO CHAR(6) NOT NULL,
    OSALARY DECIMAL(9,2),
    NSALARY DECIMAL(9,2),
    UDATE TIMESTAMP
);

CREATE TRIGGER TRIG_EMP_AFTER_UPD
    AFTER UPDATE OF SALARY ON EMPLOYEE
    REFERENCING OLD AS O NEW AS N
    FOR EACH ROW
    BEGIN
        INSERT INTO DB2ADMIN.AUDIT(USERNAME, TABLE, EMPNO, OSALARY, NSALARY, UDATE)
        VALUES (USER, 'EMPLOYEE', O.EMPNO, O.SALARY, N.SALARY, CURRENT_TIMESTAMP);
    END;

SELECT EMPNO, SALARY FROM EMPLOYEE
WHERE EMPNO = '000010';

UPDATE EMPLOYEE
SET SALARY = 20000
WHERE EMPNO = '000010';