SET SCHEMA FN71677;

CREATE FUNCTION F_GET_EMP_INFO_BY_DEPTNO(P_DEPTNO CHAR(3))
RETURNS TABLE (EMPNAME VARCHAR(50), EMAIL VARCHAR(30), PHONE CHAR(10) )
RETURN
    SELECT FNAME || ' ' || LNAME, EMAIL, PHONE
    FROM EMPLOYEES
    WHERE DEPTNO = P_DEPTNO;

SELECT D.deptname, T.*
FROM TABLE(FN71677.F_GET_EMP_INFO_BY_DEPTNO('100')) T, DEPARTMENTS D
WHERE D.DEPTNO = '100';


CREATE FUNCTION F_GET_EMP_INFO_BY_JOBID(P_TITLE VARCHAR(30))
RETURNS TABLE (DEPTNAME VARCHAR(30), EMPNAME VARCHAR(50), JOBTITLE VARCHAR(30), SALARY DECIMAL(9,2) )
RETURN
    SELECT DEPTNAME, FNAME || ' ' || LNAME, TITLE, SALARY
    FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
    WHERE E.DEPTNO = D.DEPTNO AND E.JOBID = J.JOBID
    AND   E.JOBID IN (SELECT JOBID FROM JOBS
                      WHERE INSTR(LOWER(TITLE), LOWER(P_TITLE)) > 0);

SELECT *
FROM TABLE(FN71677.F_GET_EMP_INFO_BY_JOBID('PROG')) T
ORDER BY T.JOBTITLE;

SELECT *
FROM TABLE(FN71677.F_GET_EMP_INFO_BY_JOBID('SALES')) T
ORDER BY T.JOBTITLE;